"""
Scenario definitions for messy meeting audio generation.

Each scenario defines speakers, their text, timing offsets, and expected
keywords for validation. Audio is generated by generate_audio.py using
edge-tts + numpy signal processing.
"""

VOICES = {
    "Alice": "en-US-JennyNeural",
    "Bob": "en-US-GuyNeural",
    "Carol": "ru-RU-SvetlanaNeural",
}

# Each scenario: list of utterances with speaker, text, start_s offset,
# optional noise_db, and expected keywords for validation.

SCENARIOS = {
    "overlap": {
        "description": "Two speakers talking simultaneously — 5s overlap",
        "utterances": [
            {
                "speaker": "Alice",
                "text": "Let me walk you through the dashboard metrics and the quarterly performance indicators we discussed last week",
                "start_s": 0.0,
                "keywords": ["dashboard", "metrics", "quarterly", "performance"],
            },
            {
                "speaker": "Bob",
                "text": "The backend infrastructure needs a complete overhaul of the database connection pooling system",
                "start_s": 5.0,
                "keywords": ["backend", "infrastructure", "database", "pooling"],
            },
        ],
        "checks": ["keyword_attribution", "no_cross_contamination", "segment_duration", "no_duplicates"],
    },

    "long-pause": {
        "description": "12s silence mid-sentence — should split into two segments",
        "utterances": [
            {
                "speaker": "Alice",
                "text": "The deployment pipeline has three critical stages",
                "start_s": 0.0,
                "keywords": ["deployment", "pipeline", "stages"],
            },
            {
                "speaker": "Alice",
                "text": "And the final stage requires manual approval from the team lead",
                "start_s": 17.0,  # 5s speech + 12s pause
                "keywords": ["approval", "team", "lead"],
            },
        ],
        "checks": ["keyword_attribution", "segment_duration", "no_duplicates"],
    },

    "noise": {
        "description": "Background noise at -20dB mixed into speaker track",
        "utterances": [
            {
                "speaker": "Bob",
                "text": "We need to migrate the authentication service to use OAuth two point zero with proper token rotation",
                "start_s": 0.0,
                "noise_db": -20,
                "keywords": ["authentication", "OAuth", "token", "rotation"],
            },
        ],
        "checks": ["keyword_attribution", "no_hallucinations", "segment_duration", "no_duplicates"],
    },

    "interjections": {
        "description": "Short 'yeah', 'ok' between long segments",
        "utterances": [
            {
                "speaker": "Alice",
                "text": "So the product roadmap for next quarter includes three major features the customer portal redesign the analytics dashboard and the mobile notification system",
                "start_s": 0.0,
                "keywords": ["roadmap", "quarter", "features", "portal", "analytics", "mobile"],
            },
            {
                "speaker": "Bob",
                "text": "yeah",
                "start_s": 3.0,
                "keywords": [],
                "advisory": True,  # interjections may or may not pass VAD
            },
            {
                "speaker": "Bob",
                "text": "uh-huh",
                "start_s": 8.0,
                "keywords": [],
                "advisory": True,
            },
        ],
        "checks": ["keyword_attribution", "segment_duration", "no_duplicates"],
    },

    "rapid-switch": {
        "description": "A→B→A→B quick alternation, 2s each, no overlap",
        "utterances": [
            {
                "speaker": "Alice",
                "text": "The server logs show memory leaks",
                "start_s": 0.0,
                "keywords": ["server", "logs", "memory"],
            },
            {
                "speaker": "Bob",
                "text": "Which container is affected",
                "start_s": 2.5,
                "keywords": ["container", "affected"],
            },
            {
                "speaker": "Alice",
                "text": "The transcription worker pod",
                "start_s": 5.0,
                "keywords": ["transcription", "worker"],
            },
            {
                "speaker": "Bob",
                "text": "I will check the heap dumps",
                "start_s": 7.5,
                "keywords": ["heap", "dumps"],
            },
        ],
        "checks": ["keyword_attribution", "no_cross_contamination", "segment_duration", "no_duplicates"],
    },

    "multilingual": {
        "description": "Russian + English in same meeting",
        "utterances": [
            {
                "speaker": "Alice",
                "text": "Let me share the sprint velocity report with everyone",
                "start_s": 0.0,
                "keywords": ["sprint", "velocity", "report"],
                "language": "en",
            },
            {
                "speaker": "Bob",
                "text": "The API endpoint needs better error handling for timeout scenarios",
                "start_s": 6.0,
                "keywords": ["API", "endpoint", "error", "timeout"],
                "language": "en",
            },
            {
                "speaker": "Carol",
                "text": "Давайте обсудим результаты тестирования и план на следующую неделю",
                "start_s": 12.0,
                "keywords": ["результаты", "тестирования", "план", "неделю"],
                "language": "ru",
            },
        ],
        "checks": ["keyword_attribution", "no_cross_contamination", "multilingual", "no_duplicates"],
    },

    "full-messy": {
        "description": "All combined: 3 speakers + overlaps + noise + pauses + Russian",
        "utterances": [
            # Alice starts with a product update
            {
                "speaker": "Alice",
                "text": "Good morning everyone let me start with the product update we shipped the notification system last Friday",
                "start_s": 0.0,
                "keywords": ["product", "update", "notification", "shipped"],
                "language": "en",
            },
            # Bob interjects
            {
                "speaker": "Bob",
                "text": "yeah",
                "start_s": 3.0,
                "keywords": [],
                "advisory": True,
            },
            # Bob overlaps with Alice's tail
            {
                "speaker": "Bob",
                "text": "The infrastructure cost report shows we are twenty percent over budget on compute resources",
                "start_s": 9.0,
                "noise_db": -20,
                "keywords": ["infrastructure", "cost", "budget", "compute"],
                "language": "en",
            },
            # Long pause then Alice resumes
            {
                "speaker": "Alice",
                "text": "Moving on to the customer feedback the main complaint is about search latency",
                "start_s": 26.0,  # ~12s gap after Bob
                "keywords": ["customer", "feedback", "search", "latency"],
                "language": "en",
            },
            # Carol speaks Russian
            {
                "speaker": "Carol",
                "text": "Я хотела бы добавить что наша команда завершила интеграцию с платёжной системой",
                "start_s": 33.0,
                "keywords": ["команда", "завершила", "интеграцию", "платежной"],
                "language": "ru",
            },
            # Rapid switch
            {
                "speaker": "Alice",
                "text": "Great point Carol any blockers",
                "start_s": 40.0,
                "keywords": ["carol"],
                "language": "en",
            },
            {
                "speaker": "Bob",
                "text": "No blockers from my side the deployment is on track",
                "start_s": 42.5,
                "keywords": ["deployment", "track"],
                "language": "en",
            },
        ],
        "checks": [
            "keyword_attribution",
            "no_cross_contamination",
            "segment_duration",
            "draft_confirmed",
            "no_hallucinations",
            "no_duplicates",
            "multilingual",
        ],
    },
    "rapid-overlap": {
        "description": "Fast-switching overlapping speech — tests 'eaten first seconds' problem",
        "utterances": [
            # Alice starts a sentence (3s duration expected)
            {
                "speaker": "Alice",
                "text": "The deployment pipeline failed again last night during the rollout",
                "start_s": 0.0,
                "keywords": ["deployment", "pipeline", "failed", "rollout"],
                "language": "en",
            },
            # Bob interrupts at 2s — overlaps with Alice for ~1s
            {
                "speaker": "Bob",
                "text": "Wait which pipeline are you talking about the staging one",
                "start_s": 2.0,
                "keywords": ["pipeline", "staging"],
                "language": "en",
            },
            # Carol interjects "yes exactly" at 3.5s — overlaps with Bob (0.5s duration)
            {
                "speaker": "Carol",
                "text": "yes exactly",
                "start_s": 3.5,
                "keywords": [],
                "advisory": True,
            },
            # Alice responds immediately after Bob (~0.2s gap from Bob's expected end ~4s)
            {
                "speaker": "Alice",
                "text": "No the production one it broke the checkout flow",
                "start_s": 4.2,
                "keywords": ["production", "checkout"],
                "language": "en",
            },
            # Rapid A->B->A->B with 0.3s gaps
            {
                "speaker": "Bob",
                "text": "Did you check the logs",
                "start_s": 6.5,
                "keywords": ["logs"],
                "language": "en",
            },
            {
                "speaker": "Alice",
                "text": "Yes memory spike",
                "start_s": 7.8,
                "keywords": ["memory"],
                "language": "en",
            },
            {
                "speaker": "Bob",
                "text": "How much memory",
                "start_s": 9.1,
                "keywords": ["memory"],
                "language": "en",
            },
            {
                "speaker": "Alice",
                "text": "Eight gigs on a four gig container",
                "start_s": 10.4,
                "keywords": ["gigs", "container"],
                "language": "en",
            },
            # Final overlap: Bob and Alice speak simultaneously
            {
                "speaker": "Bob",
                "text": "We need to fix the memory limits right now",
                "start_s": 12.0,
                "keywords": ["memory", "limits"],
                "language": "en",
            },
            {
                "speaker": "Alice",
                "text": "I already opened a ticket for the on-call team",
                "start_s": 12.5,
                "keywords": ["ticket", "on-call"],
                "language": "en",
            },
        ],
        "checks": [
            "keyword_attribution",
            "no_cross_contamination",
            "segment_duration",
            "no_duplicates",
        ],
    },

    "chaos-meeting": {
        "description": "5-minute chaotic meeting: 3 speakers, heavy overlaps, noise, pauses, code-switching, crosstalk, filler words",
        "utterances": [
            # === Opening (0-30s): Alice leads, Bob interrupts ===
            {
                "speaker": "Alice",
                "text": "Alright everyone thanks for joining the weekly sync. I want to start with the deployment incident from last Thursday. The kubernetes cluster ran out of memory and three pods got evicted which caused a cascade failure in the payment processing pipeline.",
                "start_s": 0.0,
                "keywords": ["deployment", "incident", "kubernetes", "memory", "pods", "payment"],
                "language": "en",
            },
            {
                "speaker": "Bob",
                "text": "yeah yeah",
                "start_s": 8.0,
                "keywords": [],
                "advisory": True,
            },
            {
                "speaker": "Bob",
                "text": "right right I saw that alert at like two in the morning",
                "start_s": 14.0,
                "keywords": ["alert"],
                "language": "en",
            },
            # === Overlap zone (25-50s): Alice and Bob talk over each other ===
            {
                "speaker": "Alice",
                "text": "So the root cause analysis shows that the horizontal pod autoscaler was configured with a maximum replica count of five which was not enough for the black friday traffic spike we saw",
                "start_s": 25.0,
                "keywords": ["autoscaler", "traffic", "spike"],
                "language": "en",
            },
            {
                "speaker": "Bob",
                "text": "We should have set the ceiling to at least twenty replicas and also added a cluster autoscaler for the node pool itself",
                "start_s": 30.0,
                "noise_db": -18,
                "keywords": ["replicas", "autoscaler", "node"],
                "language": "en",
            },
            # === Carol enters with Russian context (50-80s) ===
            {
                "speaker": "Alice",
                "text": "ok",
                "start_s": 48.0,
                "keywords": [],
                "advisory": True,
            },
            {
                "speaker": "Carol",
                "text": "Извините за опоздание. Я хотела сообщить что команда бэкенда закончила рефакторинг модуля аутентификации. Все тесты проходят и мы готовы к деплою в продакшн.",
                "start_s": 50.0,
                "keywords": ["команда", "бэкенда", "рефакторинг", "аутентификации", "тесты"],
                "language": "ru",
            },
            {
                "speaker": "Bob",
                "text": "uh huh",
                "start_s": 58.0,
                "keywords": [],
                "advisory": True,
            },
            # === Long pause (80-100s): dead air then Alice resumes ===
            {
                "speaker": "Alice",
                "text": "Great work Carol. Now moving on to the database migration. We need to migrate from PostgreSQL twelve to sixteen and the estimated downtime window is about forty five minutes. The main risk is the jsonb column reindexing on the transactions table which has about three hundred million rows.",
                "start_s": 100.0,
                "keywords": ["database", "migration", "PostgreSQL", "transactions"],
                "language": "en",
            },
            # === Rapid fire discussion (115-150s) ===
            {
                "speaker": "Bob",
                "text": "Can we do a rolling migration instead of a full downtime window? I have done that before with logical replication between the old and new clusters.",
                "start_s": 118.0,
                "keywords": ["logical", "replication"],
                "language": "en",
            },
            {
                "speaker": "Alice",
                "text": "That is an option but the risk is data inconsistency during the switchover window. We would need a custom conflict resolution strategy.",
                "start_s": 127.0,
                "keywords": ["inconsistency", "switchover", "conflict", "resolution"],
                "language": "en",
            },
            {
                "speaker": "Bob",
                "text": "Fair enough let me prototype it this week and we can compare approaches on Friday",
                "start_s": 136.0,
                "keywords": ["prototype", "compare", "Friday"],
                "language": "en",
            },
            # === Carol code-switches Russian/English (150-180s) ===
            {
                "speaker": "Carol",
                "text": "У меня есть предложение по мониторингу. Мы можем использовать Prometheus с Grafana для отслеживания метрик производительности базы данных во время миграции.",
                "start_s": 150.0,
                "keywords": ["мониторингу", "метрик", "производительности"],
                "language": "ru",
            },
            {
                "speaker": "Alice",
                "text": "That is a great idea. Bob can you set up the Grafana dashboards before the migration window?",
                "start_s": 165.0,
                "keywords": ["Grafana", "dashboards"],
                "language": "en",
            },
            {
                "speaker": "Bob",
                "text": "Sure I already have a template from the last migration we did for the analytics cluster",
                "start_s": 172.0,
                "keywords": ["template", "analytics"],
                "language": "en",
            },
            # === Noisy section (180-220s): background interference ===
            {
                "speaker": "Alice",
                "text": "Next topic is the API gateway refactoring. The current nginx configuration has become unmaintainable with over two hundred location blocks and we are seeing intermittent five hundred errors under heavy load especially on the websocket endpoints.",
                "start_s": 185.0,
                "noise_db": -15,
                "keywords": ["API", "gateway", "nginx", "location"],
                "language": "en",
            },
            {
                "speaker": "Bob",
                "text": "I have been looking at envoy proxy as a replacement. It has native support for gRPC and websockets and the configuration is much more declarative.",
                "start_s": 200.0,
                "noise_db": -18,
                "keywords": ["envoy", "proxy", "gRPC", "declarative"],
                "language": "en",
            },
            # === More overlaps (220-260s) ===
            {
                "speaker": "Carol",
                "text": "Мы также должны рассмотреть вопрос безопасности. Нужно добавить rate limiting и валидацию входящих запросов на уровне шлюза.",
                "start_s": 220.0,
                "keywords": ["безопасности", "валидацию", "запросов", "шлюза"],
                "language": "ru",
            },
            {
                "speaker": "Alice",
                "text": "Absolutely we need rate limiting. Bob what is the current request throughput on the gateway?",
                "start_s": 233.0,
                "keywords": ["rate", "limiting", "throughput"],
                "language": "en",
            },
            {
                "speaker": "Bob",
                "text": "About twelve thousand requests per second at peak. The P99 latency is around forty milliseconds which is already above our SLA threshold of thirty milliseconds.",
                "start_s": 240.0,
                "keywords": ["latency", "SLA", "threshold"],
                "language": "en",
            },
            # === Wrap up (260-300s): action items ===
            {
                "speaker": "Alice",
                "text": "OK let me summarize the action items. Bob you are prototyping the rolling database migration and setting up Grafana dashboards. Carol your team will handle the authentication module deployment and set up monitoring. I will draft the API gateway migration proposal and share it by Wednesday.",
                "start_s": 265.0,
                "keywords": ["action", "items", "prototyping", "authentication", "proposal", "Wednesday"],
                "language": "en",
            },
            {
                "speaker": "Bob",
                "text": "Sounds good. One more thing can we also schedule a load test for the staging environment before the gateway changes go live?",
                "start_s": 285.0,
                "keywords": ["load", "test", "staging", "environment", "gateway"],
                "language": "en",
            },
            {
                "speaker": "Carol",
                "text": "Да конечно. Я добавлю это в план на следующий спринт. Спасибо всем хорошего дня.",
                "start_s": 295.0,
                "keywords": ["план", "спринт"],
                "language": "ru",
            },
        ],
        "checks": [
            "keyword_attribution",
            "no_cross_contamination",
            "segment_duration",
            "no_hallucinations",
            "no_duplicates",
            "multilingual",
        ],
    },
}


def get_scenario(name: str) -> dict:
    """Get a scenario by name, raising KeyError if not found."""
    if name not in SCENARIOS:
        available = ", ".join(sorted(SCENARIOS.keys()))
        raise KeyError(f"Unknown scenario '{name}'. Available: {available}")
    return SCENARIOS[name]


def list_scenarios() -> list[str]:
    """Return sorted list of scenario names."""
    return sorted(SCENARIOS.keys())
